language: clojure

lein: lein2

jdk: openjdk7

services:
  - postgresql

addons:
  postgresql: "9.3"

env:
  - POSTGRES_JDBC="jdbc:postgres://postgresql:@localhost:5432/travis_ci_test"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: lein test
